query BlogQuery {
    blog {
        items {
            id
            title
            tags
            categories
            author {
                id
                name
                company
            }
        }
    }
}