query PostsQuery ($id: Int, $authorId: Int) {
    posts (id: $id, authorId: $authorId) {
        id
        categories
        publishDate
        summary
        tags
        title
        author {
            id
            name
            company
        }
    }
}